# SPDX-License-Identifier: MPL-2.0
name: Scorecards supply-chain security

on:
  workflow_dispatch:
  branch_protection_rule:
  schedule:
    - cron: '23 4 * * 1'

permissions: read-all

jobs:
  analysis:
    uses: hyperpolymath/standards/.github/workflows/scorecard-reusable.yml@257869d3061d5a8ed1529bf34225d90a2416d51a
    permissions:
      actions: read
      contents: read
      security-events: write
      id-token: write
    secrets: inherit
